[project]
name = "tap-sdk-py"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "eventemitter>=0.2.0",
    "requests>=2.32.4",
    "websockets>=15.0.1",
]
